// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zphspfrxugumrgyaorbe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpwaHNwZnJ4dWd1bXJneWFvcmJlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc2MDYwOTcsImV4cCI6MjA3MzE4MjA5N30.QUm-qAr-OIWWNu8-IJ5oBSCAlpYYHvLzymrfLI4_54M";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});